### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [oleksandrblazhko/ai-192-savchenko#3]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
6) Відомо, що з серпня 2021 року GitHub-сервер забороняє клонувати Private GitHub-репозиторії 
через процедуру аутентифікації на основі паролю. Опишіть, будь ласка, 
інші два засоби безпеки, які дозволяють зробити таке клонування.

**Comment by quepena** [comment]
Технологія єдиного входу (Single sign-on SSO) – метод аутентифікації, який дозволяє
користувачам безпечно аутентифікуватися одразу у кількох програмах, використовуючи один

набір облікових даних, який зберігається у спеціальній структурі даних Token. Token-
структура може містити, наприклад, email-адресу та інші додаткові дані як ідентифікатори,

яки можуть однозначно ідентифікувати систему, що створила Token.

**Comment by beatasavchenko** [comment]
Після заборони клонування приватних репозиторіїв через аутентифікацію на основі паролю було запропоновано інші засоби безпеки, наприклад за допомогою HTTPS та SSH. Перший спосіб вимагає створення токену Personal Access Token (PAT). Цей токен можна згенерувати за допомогою Github, після чого його можна використати для безпечного клонування приватного репозиторію. Другий спосіб використовує SSH (Secure Shell), який є мережевим протоколом, котрий використовує два ключи: відкритий та закритий. Так, можна згенерувати ключі за допомогою команди ssh-keygen (вона сформує відкритий та закритий ключі), після чого відкритий ключ розмістити на Github. Після реєстрації ключа можна безпечно клонувати приватний репозиторій.

**Comment by oleksandrblazhko** [comment]
Рішення прийнято.
Оцінка = 2 бали
